
export const WORK_CLIMATE_SURVEY_SCALE = [
    "Totalmente en desacuerdo",
    "En desacuerdo",
    "Neutral",
    "De acuerdo",
    "Totalmente de acuerdo"
];

export const CLIMATE_QUESTIONS = [
    "Mi trabajo me parece retador, por eso lo realizó con calidad.",
    "Mi jefe se preocupa por mis resultados y me asesora en la implementación de estrategias para mejorarlos.",
    "Mi sueldo y prestaciones son similares a los de otras empresas.",
    "Nos preocupamos por la calidad de nuestros productos.",
    "Los objetivos de mi área son claros y específicos.",
    "El personal de la empresa no admite errores y pretextos.",
    "Nos imparten cursos de capacitación.",
    "Los jefes apoyan y asesoran a su gente.",
    "Estoy a gusto trabajando en la empresa.",
    "Somos en mi área, un excelente equipo de trabajo.",
    "Mi jefe nos informa lo que se espera de nosotros, planes, objetivos, métricos etc.",
    "Conozco bien como está organizada la empresa y quien depende de quien.",
    "Mi jefe es justo al aplicar medidas disciplinarias.",
    "Vivimos un ambiente de innovación en la empresa.",
    "Mis objetivos son alcanzables.",
    "Mis compañeros son ingeniosos y se preocupan por hacer el mejor trabajo.",
    "La empresa promueve una cultura de seguridad e higiene.",
    "Mi jefe acostumbra decirme \"Por Favor\" y \"Gracias\" al pedirme las cosas.",
    "Cuando necesito algo en la empresa sé perfectamente a que departamento o persona dirigirme.",
    "Se percibe un espíritu de colaboración en esta empresa.",
    "Realmente siento como si los problemas de la organización fueran míos.",
    "Trabajamos con tecnología avanzada.",
    "Todos en la empresa tenemos buena disposición para tratar bien a los visitantes, clientes, proveedores etc.",
    "Conozco los beneficios adicionales a mi sueldo.",
    "Se han implementado cambios para mejorar los procesos.",
    "Conozco bien a que se dedica la empresa y lo que pretende lograr a mediano y largo plazo.",
    "Tengo claro lo que se espera de mí en el trabajo.",
    "Tratamos de aprender de los errores del pasado, no vivimos en él.",
    "Mi jefe me capacita adecuadamente, para el efectivo desarrollo de las funciones de mi puesto.",
    "Cuento con el mobiliario adecuado y necesario para desarrollar mis funciones.",
    "Los cursos que se han dado en la empresa, han sido de utilidad práctica para el mejoramiento de resultados.",
    "Acepto y me adapto a los cambios fácilmente.",
    "Cuento con la información que necesito a tiempo para realizar eficientemente mi trabajo.",
    "Mi espacio físico de trabajo es adecuado.",
    "Mi jefe me escucha en mis problemas y trata de apoyarme en la medida de lo posible.",
    "La empresa se esfuerza por ofrecer los productos con la mejor calidad.",
    "La empresa desarrolla y promueve a su personal.",
    "La empresa reconoce mis logros y aportaciones.",
    "Los baños tienen la higiene adecuada que requerimos.",
    "Mi jefe motiva a su equipo de trabajo.",
    "Se respira un ambiente de confianza y estabilidad.",
    "Mis compañeros me ayudan.",
    "La comunicación entre las diferentes áreas es fluida y adecuada.",
    "Trabajamos el horario establecido.",
    "Mi jefe se expresa bien de la empresa.",
    "Los puestos similares de las diferentes áreas de la empresa, tienen sueldos y beneficios equivalentes.",
    "La empresa ha difundido bien, entre el personal la idea de calidad y como lograrla.",
    "Existe una comunicación buena entre los miembros de mi departamento.",
    "Las políticas y procedimientos facilitan el trabajo.",
    "Nos otorgan la capacitación suficiente.",
    "Estoy comprometido con la organización.",
    "Existe una comunicación frecuente, abierta y clara entre mi jefe y yo.",
    "Los compañeros de todos los departamentos, reconocen el trabajo del personal de otras áreas.",
    "Se nos proporciona información importante y oportuna para realizar nuestro trabajo.",
    "Contamos con equipo y herramientas suficientes para hacer nuestro trabajo.",
    "El personal hace todo lo posible para mantener los estándares de limpieza y orden.",
    "Contamos con beneficios adicionales y superiores a los que tienen en otras empresas.",
    "El personal tiene conciencia y evita en todo momento el desperdicio de recursos (luz, agua, etc.).",
    "Mis compañeros se preocupan por cumplir sus objetivos.",
    "El comedor cuenta con las instalaciones e higiene adecuadas.",
    "El jefe de mi área está consciente de que los resultados son por esfuerzo de todos.",
    "La coordinación entre mi área y otras es buena.",
    "En mi puesto, hacer las cosas bien y mejorarlas día a día es importante.",
    "Me siento orgulloso de trabajar en esta empresa.",
    "Vivimos un ambiente de responsabilidad compartida.",
    "Manejo y resguardo de forma segura y adecuada los bienes y propiedades de la empresa, en el entendido que es mi responsabilidad hacerlo."
];
